### PR TITLE
Jest react

### PR DESCRIPTION
**Pull request by jchen0506**
Basic configuration of enzyme with jest and babel

### CODE REVIEW

**Comment by jchen0506** [comment]
@area363 Hey Don. Can you review my PR about front end test. I just got the configuration done and only have 2 basic test for now.

**Comment by area363** [comment]
Hey Jing looks good! Btw how are you doing coverage test? Can jest also do them? Btw you might want to gitignore coverage reports so you dont have to push those everytime you do the tests

**Comment by jchen0506** [comment]
@area363 Yes, I setup a test with coverage command in package.json. Jest come with this function. Ah, I will add the coverage report to gitignore, thanks for reminding me!

**Comment by jchen0506** [comment]
@area363 Hey Don, I updated on this branch, adding more tests to each component and also gitignored the coverage report folder except the report summary in index.html. Could you review it when you get a chance. Thank you!

**Comment by jchen0506** [comment]
gitignored everything in coverage folder except for the index.html coverage report

**Pull request merged**
